import {
  calculateThresholdEdge,
  createThresholdMarker,
  getInjuryResistance,
  getThresholdDefense,
  getThresholdSeverityBand,
  getThresholdTargetNumber,
  getTotalSeverityPressure,
  isThresholdTriggered,
  normalizeNonNegativeInteger,
} from "../helpers/injury-thresholds.mjs";

/**
 * Extend the base Actor document by defining a custom roll data structure which is ideal for the Simple system.
 * @extends {Actor}
 */
export class SWNActor extends Actor {
  /** @override */
  async _preUpdate(changed, options, user) {
    await super._preUpdate(changed, options, user);

    const changedSystem = changed.system ?? {};
    const hasNestedChange = Object.hasOwn(changedSystem, "injuryResistance");
    const flatKey = "system.injuryResistance";
    const hasFlatChange = Object.hasOwn(changed, flatKey);

    if (!hasNestedChange && !hasFlatChange) return;

    const actingUser = typeof user === "string" ? game.users?.get(user) : user;
    const isGM = Boolean(actingUser?.isGM ?? game.user?.isGM);

    if (!isGM) {
      if (hasNestedChange) delete changedSystem.injuryResistance;
      if (hasFlatChange) delete changed[flatKey];
      if (changed.system && Object.keys(changed.system).length === 0) delete changed.system;
      ui.notifications?.warn(game.i18n.localize("swnr.notifications.injuryResistanceGMOnly"));
      return;
    }

    if (hasNestedChange) changedSystem.injuryResistance = normalizeNonNegativeInteger(changedSystem.injuryResistance);
    if (hasFlatChange) changed[flatKey] = normalizeNonNegativeInteger(changed[flatKey]);
  }

  /** @override */
  prepareData() {
    // Prepare data for the actor. Calling the super version of this executes
    // the following, in order: data reset (to clear active effects),
    // prepareBaseData(), prepareEmbeddedDocuments() (including active effects),
    // prepareDerivedData().
    super.prepareData();
  }

  /** @override */
  prepareBaseData() {
    // Data modifications in this step occur before processing embedded
    // documents or derived data.
  }

  /**
   * @override
   * Augment the actor source data with additional dynamic data that isn't
   * handled by the actor's DataModel. Data calculated in this step should be
   * available both inside and outside of character sheets (such as if an actor
   * is queried and has a roll executed directly from it).
   */
  prepareDerivedData() {
    const actorData = this;
    const flags = actorData.flags.swnr || {};
  }

  /**
   *
   * @override
   * Augment the actor's default getRollData() method by appending the data object
   * generated by the its DataModel's getRollData(), or null. This polymorphic
   * approach is useful when you have actors & items that share a parent Document,
   * but have slightly different data preparation needs.
   */
  getRollData() {
    return { ...super.getRollData(), ...(this.system.getRollData?.() ?? null) };
  }

  /**
  * @override
  * Override the standard permission test for an Item.
  * Determine default artwork based on the provided item data.
  * @param {ItemData} itemData  The source item data.
  * @returns {{img: string}}    Candidate item image.
  */
  rollInitiative(options = {}) {
    // For starship actors, use the pilot's initiative.
    if (this.type === "ship") {
      const pilotId = this.system.roles.bridge;
      if (pilotId && pilotId !== "") {
        const pilot = game.actors?.get(pilotId);
        if (pilot && pilot.type === "character") {
          const intMod = pilot.system.stats.int.mod;
          const dexMod = pilot.system.stats.dex.mod;
          const mod = intMod >= dexMod ? intMod : dexMod;
          let tweakMod = pilot.system.tweak?.initiative.mod || '';
          if (tweakMod !== '') {
            tweakMod = ` + ${tweakMod}`;
          }
          // Use pilot's advInit flag if set.
          const adv = pilot.system?.tweak?.advInit || false;
          const formula = adv ? `2d8kh1 + ${mod}` : `1d8 + ${mod}${tweakMod}`;
          return new Roll(formula, pilot.getRollData());
        }
      }
    }
  
    // Regular initiative roll.
    const adv = this.system?.tweak?.advInit || false;
    let tweakMod = this.system.tweak?.initiative?.mod || '';
    if (tweakMod !== '') {
      tweakMod = ` + ${tweakMod}`;
    }
    const formula = adv
      ? `2d8kh1 + @stats.dex.mod ${tweakMod}`
      : `1d8 + @stats.dex.mod ${tweakMod}`;
    return new Roll(formula, this.getRollData());
  }
  
  static getDefaultArtwork(itemData) {
    let itemType = itemData.type;
    if (itemType in CONFIG.SWN.defaultImg) {
      return { img: `${CONFIG.SWN.actorIconPath}/${CONFIG.SWN.defaultImg[itemType]}`,
              texture: { src: `${CONFIG.SWN.actorIconPath}/${CONFIG.SWN.defaultImg[itemType]}` }
       };
    } else {
      return { texture: { src: this.DEFAULT_ICON } };
    }
  }

  /**
   * Calculate wound and injury increases based on severity thresholds
   * @param {number} severity - The calculated severity value
   * @returns {{ injuryIncrease: number, woundIncrease: number }}
   */
  _calculateWoundThresholds(severity) {
    let injuryIncrease = 1;
    let woundIncrease = 0;

    if (severity >= 11) {
      woundIncrease = 1;
    }
    if (severity >= 16) {
      woundIncrease += (severity - 15);
    }

    return { injuryIncrease, woundIncrease };
  }

  /**
   * Roll for injury location (1d12)
   * @returns {Promise<{location: string, locationIcon: string, side: string, locationRoll: number}>}
   */
  async _rollInjuryLocation() {
    const locationRoll = new Roll("1d12");
    await locationRoll.roll();
    const locationResult = locationRoll.total;

    let location = "";
    let locationIcon = "";
    let side = "";
    if (locationResult <= 2) {
      location = "arm";
      locationIcon = "hand";
      const sideRoll = new Roll("1d2");
      await sideRoll.roll();
      side = sideRoll.total === 1 ? "Left " : "Right ";
    } else if (locationResult <= 4) {
      location = "leg";
      locationIcon = "person-walking";
      const sideRoll = new Roll("1d2");
      await sideRoll.roll();
      side = sideRoll.total === 1 ? "Left " : "Right ";
    } else if (locationResult <= 9) {
      location = "torso";
      locationIcon = "vest";
    } else {
      location = "head";
      locationIcon = "head-side";
    }

    return { location, locationIcon, side, locationRoll: locationResult };
  }

  /**
   * Get effect description for an injury based on location and severity
   * @param {string} location - Body part (arm, leg, torso, head)
   * @param {string} side - Left/Right prefix for limbs
   * @param {number} severity - Severity value
   * @returns {string}
   */
  _getInjuryEffectDescription(location, side, severity) {
    let effectDescription = "";
    let duration = severity < 11 ? severity : "Until healed";

    if (location === "arm") {
      effectDescription = `${side}arm disabled for ${duration} days. Cannot hold items, drops anything held.`;
    } else if (location === "leg") {
      effectDescription = `${side}leg disabled for ${duration} days. Falls prone, movement halved.`;
    } else if (location === "torso") {
      effectDescription = `Blood Loss for ${duration} days. Max HP reduced by 1 per HD.`;
    } else if (location === "head") {
      effectDescription = `Concussed for ${duration} days. Acts last in initiative, INT check DC 12 to cast spells.`;
    }

    if (severity >= 11) {
      effectDescription += " Character falls unconscious.";
      if (severity < 16) {
        effectDescription += " Physical save to avoid permanent injury.";
      }
    }

    if (severity >= 16) {
      effectDescription += ` Takes ${severity - 15} additional wounds.`;
    }

    return effectDescription;
  }

  /**
   * Apply wounds from death & dismemberment system
   * @param {number} excessDamage - Damage that exceeded current HP
   */
  async applyWounds(excessDamage) {
    // Only characters and NPCs can receive injuries (Fix 3)
    if (this.type !== "character" && this.type !== "npc") {
      console.log(`SWNR | Skipping wounds for non-character actor type: ${this.type}`);
      return;
    }

    // Roll for location (1d12)
    const { location, locationIcon, side, locationRoll: locationRollValue } = await this._rollInjuryLocation();

    // Calculate severity
    const injuries = this.system.injuries || 0;
    const critResistance = this.system.critResistance || 0;
    const severityRoll = new Roll("1d12");
    await severityRoll.roll();
    // Fix 4: Ensure severity is never negative
    const severity = Math.max(0, severityRoll.total + (injuries * 2) + excessDamage - critResistance);

    // Store current values before updating
    const woundsBefore = this.system.wounds || 0;

    // Calculate wound thresholds using helper method (Fix 8)
    const { injuryIncrease, woundIncrease } = this._calculateWoundThresholds(severity);

    await this.update({
      "system.injuries": injuries + injuryIncrease,
      "system.wounds": woundsBefore + woundIncrease
    });

    // Generate effect description using helper
    const effectDescription = this._getInjuryEffectDescription(location, side, severity);

    // Create chat message
    const template = "systems/swnr/templates/chat/wound-roll.hbs";
    const chatData = {
      actor: this,
      location: side + location.charAt(0).toUpperCase() + location.slice(1),
      locationIcon: locationIcon,
      locationRoll: locationRollValue,
      severityRoll: severityRoll.total,
      injuries: injuries,
      injuryContribution: injuries * 2,
      excessDamage: excessDamage,
      critResistance: critResistance,
      severity: severity,
      injuryBefore: injuries,
      injuryAfter: injuries + injuryIncrease,
      woundBefore: woundsBefore,
      woundAfter: woundsBefore + woundIncrease,
      effectDescription: effectDescription
    };
    
    const chatContent = await renderTemplate(template, chatData);
    const rollMode = game.settings.get("core", "rollMode");
    const messageData = {
      speaker: ChatMessage.getSpeaker({ actor: this }),
      content: chatContent
    };
    
    ChatMessage.implementation.applyRollMode(messageData, rollMode);
    await ChatMessage.create(messageData);
  }

  /**
   * Apply critical injury from critical hit when HP > 0
   * @param {number} hpPercentage - Current HP as a fraction of max HP (0-1)
   */
  async applyCriticalInjury(hpPercentage) {
    // Only characters and NPCs can receive injuries (Fix 3)
    if (this.type !== "character" && this.type !== "npc") {
      console.log(`SWNR | Skipping critical injury for non-character actor type: ${this.type}`);
      return;
    }

    // Roll for location (1d12)
    const { location, locationIcon, side, locationRoll: locationRollValue } = await this._rollInjuryLocation();

    // Determine severity die based on HP percentage
    // HP >= 50% = 1d6 (minor), HP < 50% = 1d8 (moderate)
    const isMinor = hpPercentage >= 0.5;
    const severityDie = isMinor ? "1d6" : "1d8";
    const injuryType = isMinor ? "minor" : "moderate";

    // Calculate severity: severityDie + (injuries × 1) - critResistance
    const injuries = this.system.injuries || 0;
    const critResistance = this.system.critResistance || 0;
    const severityRoll = new Roll(severityDie);
    await severityRoll.roll();
    // Fix 4: Ensure severity is never negative
    const severity = Math.max(0, severityRoll.total + injuries - critResistance);

    // Store current values before updating
    const woundsBefore = this.system.wounds || 0;

    // Calculate wound thresholds using helper method (Fix 8)
    const { injuryIncrease, woundIncrease } = this._calculateWoundThresholds(severity);

    await this.update({
      "system.injuries": injuries + injuryIncrease,
      "system.wounds": woundsBefore + woundIncrease
    });

    // Generate effect description using helper
    const effectDescription = this._getInjuryEffectDescription(location, side, severity);

    // Create chat message
    const template = "systems/swnr/templates/chat/critical-injury.hbs";
    const chatData = {
      actor: this,
      location: side + location.charAt(0).toUpperCase() + location.slice(1),
      locationIcon: locationIcon,
      locationRoll: locationRollValue,
      severityDie: severityDie,
      severityRoll: severityRoll.total,
      injuries: injuries,
      injuryContribution: injuries,  // Critical injuries use injuries × 1
      critResistance: critResistance,
      severity: severity,
      injuryType: injuryType,
      hpPercentage: Math.round(hpPercentage * 100),
      currentHp: this.system.health.value,
      maxHp: this.system.health.max,
      injuryBefore: injuries,
      injuryAfter: injuries + injuryIncrease,
      woundBefore: woundsBefore,
      woundAfter: woundsBefore + woundIncrease,
      effectDescription: effectDescription
    };

    const chatContent = await renderTemplate(template, chatData);
    const rollMode = game.settings.get("core", "rollMode");
    const messageData = {
      speaker: ChatMessage.getSpeaker({ actor: this }),
      content: chatContent
    };

    ChatMessage.implementation.applyRollMode(messageData, rollMode);
    await ChatMessage.create(messageData);
  }

  getThresholdAttemptMarker(key) {
    return this.getFlag("swnr", "thresholdInjuryAttempts")?.[key] ?? null;
  }

  async claimThresholdAttempt(key) {
    const markers = foundry.utils.deepClone(this.getFlag("swnr", "thresholdInjuryAttempts") ?? {});
    if (markers[key]) return false;
    markers[key] = createThresholdMarker();
    await this.setFlag("swnr", "thresholdInjuryAttempts", markers);
    return true;
  }

  _getThresholdInjuryEffectDescription(location, side, bandLabel) {
    const locationName = `${side}${location}`;
    const band = bandLabel.charAt(0).toUpperCase() + bandLabel.slice(1);
    return `${band} threshold injury affecting the ${locationName}. Apply table effects or GM adjudication appropriate to the wound.`;
  }

  _escapeHtml(value) {
    if (foundry.utils?.escapeHTML) return foundry.utils.escapeHTML(String(value ?? ""));
    const element = document.createElement("div");
    element.textContent = String(value ?? "");
    return element.innerHTML;
  }

  async applyThresholdInjury({
    thresholdContext,
    damageRole,
    targetToken,
    preDamageHp,
    maxHp,
    sourceMessageId,
    sourceMessageUuid,
  } = {}) {
    if (this.type !== "character" && this.type !== "npc") {
      return { thresholdEligible: false, thresholdAttempted: false, thresholdSkippedReason: "actor-type" };
    }

    const attack = thresholdContext?.attack;
    const defense = getThresholdDefense(this, {
      useCWNArmor: game.settings.get("swnr", "useCWNArmor"),
      isMelee: Boolean(attack?.isMelee ?? attack?.sourceItemSnapshot?.isMelee),
    });
    const edgeResult = calculateThresholdEdge({
      attackTotal: attack?.attackTotal,
      defense,
      naturalDie: attack?.naturalDie,
    });
    if (!edgeResult.eligible) {
      return {
        thresholdEligible: false,
        thresholdAttempted: false,
        thresholdSkippedReason: edgeResult.reason,
      };
    }

    const injuryResistance = getInjuryResistance(this);
    const targetNumber = getThresholdTargetNumber({ injuryResistance, edge: edgeResult.edge });
    const thresholdRoll = new Roll("1d10");
    await thresholdRoll.roll();
    const thresholdTriggered = isThresholdTriggered({
      dieTotal: thresholdRoll.total,
      targetNumber,
    });

    const baseOutcome = {
      thresholdEligible: true,
      thresholdAttempted: true,
      thresholdTriggered,
      thresholdRoll: thresholdRoll.total,
      targetNumber,
      edge: edgeResult.edge,
      injuryResistance,
      defense,
      damageRole,
    };

    if (!thresholdTriggered) return baseOutcome;

    const severityPressure = getTotalSeverityPressure({
      weaponFormula: attack?.baseDamageFormula ?? attack?.sourceItemSnapshot?.baseDamageFormula,
      preDamageHp,
      maxHp,
      existingInjuries: this.system.injuries,
    });
    const severityRoll = new Roll("1d6");
    await severityRoll.roll();
    const severityScore = severityRoll.total + severityPressure;
    const severityBand = getThresholdSeverityBand(severityScore);
    const { location, locationIcon, side, locationRoll: locationRollValue } = await this._rollInjuryLocation();
    const displayLocation = side + location.charAt(0).toUpperCase() + location.slice(1);
    const effectDescription = this._getThresholdInjuryEffectDescription(location, side, severityBand.label);
    const injuriesBefore = this.system.injuries || 0;
    const injuriesAfter = injuriesBefore + (severityBand.persistent ? 1 : 0);

    const updates = {};
    if (severityBand.persistent) updates["system.injuries"] = injuriesAfter;
    if (Object.keys(updates).length) await this.update(updates);

    const itemName = `${severityBand.label.charAt(0).toUpperCase() + severityBand.label.slice(1)} Injury: ${displayLocation}`;
    await this.createEmbeddedDocuments("Item", [{
      name: itemName,
      type: "injury",
      system: {
        severity: severityBand.key,
        location: displayLocation,
        source: attack?.sourceItemSnapshot?.name || "Attack",
        mechanicalEffect: effectDescription,
        persistent: severityBand.persistent,
        severityScore,
        locationRoll: locationRollValue,
        description: effectDescription,
      },
    }]);

    const sourceMessage = sourceMessageUuid ? await fromUuid(sourceMessageUuid) : game.messages?.get(sourceMessageId);
    const hiddenTarget = Boolean(targetToken?.document?.hidden);
    const template = "systems/swnr/templates/chat/threshold-injury-roll.hbs";
    const chatData = {
      actor: this,
      targetLabel: hiddenTarget ? game.i18n.localize("swnr.injury.hiddenTarget") : (targetToken?.name || this.name),
      weaponName: attack?.sourceItemSnapshot?.name || game.i18n.localize("swnr.injury.unknownSource"),
      location: displayLocation,
      locationIcon,
      severityBand,
      severityScore,
      thresholdRoll: thresholdRoll.total,
      targetNumber,
      edge: edgeResult.edge,
      injuryResistance,
      defense,
      severityRoll: severityRoll.total,
      severityPressure,
      injuriesBefore,
      injuriesAfter,
      effectDescription,
      config: CONFIG.SWN,
      user: game.user,
    };
    const chatContent = await renderTemplate(template, chatData);
    const messageData = {
      speaker: hiddenTarget ? { alias: game.i18n.localize("swnr.injury.hiddenTarget") } : ChatMessage.getSpeaker({ actor: this }),
      content: chatContent,
      whisper: sourceMessage?.whisper,
      blind: sourceMessage?.blind,
    };

    await ChatMessage.create(messageData);
    const gmUsers = game.users?.filter((user) => user.isGM).map((user) => user.id) ?? [];
    if (gmUsers.length) {
      await ChatMessage.create({
        speaker: ChatMessage.getSpeaker({ actor: this }),
        whisper: gmUsers,
        content: `<p class="swnr threshold-gm-summary"><strong>${this._escapeHtml(chatData.targetLabel)}</strong>: threshold ${thresholdRoll.total} vs ${targetNumber}; Edge ${edgeResult.edge}, resistance ${injuryResistance}, defense ${defense}; severity ${severityRoll.total} + ${severityPressure} = ${severityScore}.</p>`,
      });
    }
    return {
      ...baseOutcome,
      severityBand,
      severityScore,
      injuryItemCreated: true,
      injuryPersistent: severityBand.persistent,
    };
  }
}
